version: '3.8'

services:
  web:
    build: .
    network_mode: "host"  # Use host network stack
    volumes:
      - ./data:/app/data
      - ./download:/app/download
      - ./app:/app/app
    environment:
      - FLASK_ENV=production
    working_dir: /app
    restart: unless-stopped
